import type { ThemeId } from ".";

// Textos de la interfaz. Cada tema de juego pisa solo lo que quiere cambiar.
const BASE = {
  "nav.info": "Información",
  "nav.skills": "Habilidades",
  "nav.projects": "Proyectos",
  "nav.contact": "Contacto",
  cta: "Nuevo proyecto",
  "hero.role": "Desarrollo web con",
  "hero.primary": "Ver proyectos",
  "hero.secondary": "Contactame",
  "hero.cv": "Descargar CV",
  "contact.cvQ": "¿Querés mi CV completo?",
  "skills.title": "Inventario de Habilidades",
  "skills.hint": "Arrastralas para ordenarlas a tu gusto",
  "projects.title": "Inventario de Proyectos",
  "projects.web": "Sitio Web",
  "projects.private": "Privado",
  "projects.locked": "Slot en desarrollo. Próximamente se revelará un nuevo proyecto.",
  "projects.soon": "Próximamente",
  "contact.title": "¡Hablemos de tu proyecto!",
  "contact.name": "Nombre",
  "contact.email": "Email",
  "contact.message": "Contame sobre tu idea...",
  "contact.send": "Enviar mensaje",
  "contact.whatsappQ": "¿Preferís hablar directamente por WhatsApp?",
  "contact.whatsapp": "Chatear por WhatsApp",
};

export type TextoKey = keyof typeof BASE;

const POR_TEMA: Partial<Record<ThemeId, Partial<Record<TextoKey, string>>>> = {
  minecraft: {
    "nav.info": "Perfil",
    "nav.skills": "Inventario",
    "nav.projects": "Construcciones",
    "nav.contact": "Multijugador",
    cta: "Crear mundo",
    "hero.role": "Construyendo bloque a bloque con",
    "hero.primary": "Un jugador",
    "hero.secondary": "Multijugador",
    "hero.cv": "Craftear mi CV",
    "contact.cvQ": "¿Querés llevarte mi libro?",
    "skills.title": "Inventario",
    "skills.hint": "Arrastrá los bloques para acomodar tu inventario",
    "projects.title": "Mis construcciones",
    "projects.web": "Entrar al mundo",
    "projects.private": "Mundo privado",
    "projects.locked": "Este chunk todavía no se generó. Seguí explorando.",
    "projects.soon": "Sin generar",
    "contact.title": "Unirse a la partida",
    "contact.name": "Nombre de jugador",
    "contact.email": "Dirección del servidor (tu email)",
    "contact.message": "Escribí en el chat...",
    "contact.send": "Enviar al chat",
    "contact.whatsappQ": "¿Preferís un mensaje directo?",
    "contact.whatsapp": "Susurrar por WhatsApp",
  },
  silenthill: {
    "nav.info": "Diario",
    "nav.skills": "Objetos",
    "nav.projects": "Memos",
    "nav.contact": "Carta",
    cta: "Nueva partida",
    "hero.role": "Perdido en la niebla con",
    "hero.primary": "Entrar al pueblo",
    "hero.secondary": "Escribir una carta",
    "hero.cv": "Recoger el memo · CV",
    "contact.cvQ": "Encontraste un memo en el piso.",
    "skills.title": "Objetos",
    "skills.hint": "Reordená lo que llevás encima",
    "projects.title": "Memos encontrados",
    "projects.web": "Abrir la puerta",
    "projects.private": "Cerrada con llave",
    "projects.locked": "La puerta está trabada. No se puede abrir desde este lado.",
    "projects.soon": "Cerrado",
    "contact.title": "Escribime una carta",
    "contact.name": "Tu nombre",
    "contact.email": "Dónde responderte",
    "contact.message": "Querido Lautaro...",
    "contact.send": "Enviar la carta",
    "contact.whatsappQ": "¿Escuchás estática? Es la radio.",
    "contact.whatsapp": "Sintonizar WhatsApp",
  },
  thelastofus: {
    "nav.info": "Perfil",
    "nav.skills": "Mejoras",
    "nav.projects": "Artefactos",
    "nav.contact": "Señal",
    cta: "Nueva partida",
    "hero.role": "Sobreviviendo con",
    "hero.primary": "Continuar",
    "hero.secondary": "Buscar la luz",
    "hero.cv": "Recoger el manual · CV",
    "contact.cvQ": "Encontraste un manual de entrenamiento.",
    "skills.title": "Mejoras",
    "skills.hint": "Arrastrá los manuales para ordenarlos",
    "projects.title": "Artefactos",
    "projects.web": "Explorar",
    "projects.private": "Zona en cuarentena",
    "projects.locked": "Zona sin explorar. Se necesita más tiempo para cruzarla.",
    "projects.soon": "Sin explorar",
    "contact.title": "Enviar una señal",
    "contact.name": "Nombre",
    "contact.email": "Frecuencia (email)",
    "contact.message": "Contame qué necesitás...",
    "contact.send": "Transmitir",
    "contact.whatsappQ": "¿Preferís un canal directo?",
    "contact.whatsapp": "Abrir canal por WhatsApp",
  },
  gta6: {
    "nav.info": "Perfil",
    "nav.skills": "Stats",
    "nav.projects": "Misiones",
    "nav.contact": "Teléfono",
    cta: "Nuevo golpe",
    "hero.role": "Haciendo negocios en Leonida con",
    "hero.primary": "Ver misiones",
    "hero.secondary": "Llamame",
    "hero.cv": "Descargar expediente · CV",
    "contact.cvQ": "¿Querés el expediente completo?",
    "skills.title": "Estadísticas",
    "skills.hint": "Arrastrá para reordenar tus stats",
    "projects.title": "Misiones",
    "projects.web": "Iniciar misión",
    "projects.private": "Misión secreta",
    "projects.locked": "Misión bloqueada. Completá las anteriores para desbloquearla.",
    "projects.soon": "Bloqueada",
    "contact.title": "Llamada entrante",
    "contact.name": "Nombre",
    "contact.email": "Email",
    "contact.message": "Escribí tu mensaje...",
    "contact.send": "Enviar SMS",
    "contact.whatsappQ": "¿Mejor por mensaje directo?",
    "contact.whatsapp": "Abrir WhatsApp",
  },
  redead: {
    "nav.info": "Cartel",
    "nav.skills": "Alforja",
    "nav.projects": "Diario",
    "nav.contact": "Telégrafo",
    cta: "Nuevo encargo",
    "hero.role": "Forajido del código con",
    "hero.primary": "Leer el diario",
    "hero.secondary": "Mandar un telegrama",
    "hero.cv": "Llevarse el cartel · CV",
    "contact.cvQ": "El cartel completo, con todos los datos.",
    "skills.title": "Alforja",
    "skills.hint": "Acomodá lo que llevás en la alforja",
    "projects.title": "Diario de trabajos",
    "projects.web": "Visitar",
    "projects.private": "Bajo llave",
    "projects.locked": "Página en blanco. El próximo golpe todavía se está planeando.",
    "projects.soon": "Por escribir",
    "contact.title": "Enviar un telegrama",
    "contact.name": "Remitente",
    "contact.email": "Dirección postal (email)",
    "contact.message": "Escribí tu mensaje, forastero...",
    "contact.send": "Telegrafiar",
    "contact.whatsappQ": "¿Apurado? Hay un atajo.",
    "contact.whatsapp": "Galopar a WhatsApp",
  },
};

export const getTextos = (theme: ThemeId | null) => ({ ...BASE, ...(theme ? POR_TEMA[theme] : null) });
